prefix = /var/www/otyis-isp/radius
logdir = ${prefix}/log
run_dir = ${prefix}/run
modconfdir = ${prefix}/mods-config
libdir = /usr/lib/freeradius
$INCLUDE clients.conf
modules {
  $INCLUDE mods-enabled/
}
policy {
  $INCLUDE /etc/freeradius/3.0/policy.d/
}
$INCLUDE sites-enabled/
